### ISSUE TITLE
Best approach to use 3rd party Blazor controls

### ISSUE THREAD

**Issue by VR-Architect** [one1lion/maui-blazor-web-template#2]
Can you please incorporate the best way to use 3rd party Blazor controls like Syncfusion.Blazor.Charts in a centralized fashion? 

The setup requires we add 
  builder.Services.AddSyncfusionBlazor(); 

to the Program.cs file. I would prefer to only put Syncfusion in the Shared.Ui project.

Thanks

**Comment by one1lion** [comment]
I added the way that I generally register shared services across multiple projects. Normally I have sets of objects grouped together (such as State class objects, Logging, AutoMapper if I use it) in their own extension methods, but this would be a pretty good way if you're used to registering all of your services in Program.cs.

**Comment by VR-Architect** [comment]
Hey, your new code worked fantastic. I was able to get Syncfusion and Microsoft.Extensions.Http working great. I did have a CORS issue with WASM. I will create a feature request for that. You should really get more advertising about this project as it would be great for everyone!
